# Generated by Django 2.1 on 2018-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='benefits',
            field=models.TextField(max_length=500),
        ),
    ]
